const NEW_TODO = 'NEW_TODO'
const START_TODO = 'START_TODO'
const FINISH_TODO = 'FINISH_TODO'
const DELETE_TODO = 'DELETE_TODO'
const STOP_TODO = 'STOP_TODO'
const RESET_TODO = 'RESET_TODO'
const UPDATE_EVENTS = 'UPDATE_EVENTS'
const REFRESH_STATE = 'REFRESH_STATE'

export {
    NEW_TODO,
    START_TODO,
    FINISH_TODO,
    DELETE_TODO,
    STOP_TODO,
    RESET_TODO,
    UPDATE_EVENTS,
    REFRESH_STATE
}